cookie:
  expiry_days: 30
  key: cookie_signature
  name: cookie_name
credentials:
  usernames:
    datascience:
      email: datascience@mail.com
      failed_login_attempts: 0
      logged_in: false
      name: Data Science Team
      password: $2b$12$cnEz04fT84pF/7bFFEPyaObRuUDBTG80Er0A5XKhFkPcI.tewtEoi
    marketing:
      email: marketing@mail.com
      failed_login_attempts: 0
      logged_in: false
      name: Marketing Team
      password: $2b$12$XY6Vau7F7YGRIuIBvB2Zf.1LY/KBHRdIhcp8Xlq/ydo3HJFbpQWnK
